import { mkdir, stat, unlink, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { randomUUID } from "node:crypto";
import type { ConfirmedUpload, MediaStorageAdapter, UploadTarget } from "./types";
import { signToken } from "./signing";

/**
 * Local filesystem storage adapter for development and testing.
 *
 * This is a REAL, functioning implementation (not a stub that always
 * succeeds) — it writes to disk, tracks a metadata sidecar, and enforces
 * signed/expiring access exactly like the production adapter will. It is
 * not, however, suitable for a real multi-instance production deployment
 * (see docs/architecture.md Section 1 and docs/deployment.md for the
 * Supabase Storage / S3 / R2 swap-in path — same `MediaStorageAdapter`
 * interface, different implementation file).
 */

function rootDir(): string {
  const dir = process.env.STORAGE_LOCAL_DIR ?? "./.data/media";
  // turbopackIgnore: the destination is env-configured (not statically
  // analyzable), which would otherwise make the bundler trace and include
  // the entire project as potential server output. This adapter is
  // dev/test-only (see file docstring) — production uses the Supabase/S3/R2
  // adapter instead, which makes no filesystem calls at all.
  return resolve(/* turbopackIgnore: true */ process.cwd(), dir);
}

function objectPath(key: string): string {
  // `key` DOES reach here directly from a client-supplied query parameter in
  // /api/uploads/put and /api/media/read — it is NOT limited to values freshly
  // generated by buildKey() below. What actually prevents path traversal is
  // signature verification: both routes require an HMAC-signed token (see
  // src/lib/storage/signing.ts) that embeds and cryptographically binds the
  // exact key, so a client cannot substitute an arbitrary path without a
  // valid signature it cannot forge. See docs/pre-production-review.md P3-3 —
  // an earlier version of this comment overstated "we never take it from the
  // client" as the safeguard, which risked misleading a future edit (e.g. an
  // unsigned convenience endpoint reusing this helper) into believing the key
  // itself was already trusted input.
  return join(/* turbopackIgnore: true */ rootDir(), key);
}

function metaPath(key: string): string {
  return `${objectPath(key)}.meta.json`;
}

export const localStorageAdapter: MediaStorageAdapter = {
  buildKey({ organizationSlug, submissionId, answerId, extension }) {
    const safeExt = extension.replace(/[^a-z0-9]/gi, "").slice(0, 10) || "bin";
    return `${organizationSlug}/${submissionId}/${answerId}/${randomUUID()}.${safeExt}`;
  },

  async createUploadTarget(key, contentType): Promise<UploadTarget> {
    const expiresInSeconds = 15 * 60;
    const exp = Math.floor(Date.now() / 1000) + expiresInSeconds;
    const token = signToken({ key, purpose: "write", exp });
    return {
      method: "PUT",
      url: `/api/uploads/put?key=${encodeURIComponent(key)}&token=${encodeURIComponent(token)}`,
      headers: { "Content-Type": contentType },
      bodyFormat: "raw",
      expiresInSeconds,
    };
  },

  async confirmUpload(key): Promise<ConfirmedUpload | null> {
    try {
      const [fileStat, metaRaw] = await Promise.all([
        stat(objectPath(key)),
        import("node:fs/promises").then((fs) => fs.readFile(metaPath(key), "utf8")),
      ]);
      const meta = JSON.parse(metaRaw) as { contentType: string };
      return { bytes: fileStat.size, contentType: meta.contentType };
    } catch {
      return null;
    }
  },

  async getSignedReadUrl(key, expiresInSeconds) {
    const exp = Math.floor(Date.now() / 1000) + expiresInSeconds;
    const token = signToken({ key, purpose: "read", exp });
    return `/api/media/read?key=${encodeURIComponent(key)}&token=${encodeURIComponent(token)}`;
  },

  async deleteObject(key) {
    await Promise.allSettled([unlink(objectPath(key)), unlink(metaPath(key))]);
  },
};

/** Internal helper used only by the /api/uploads/put route handler. */
export async function writeLocalObject(key: string, contentType: string, data: Buffer): Promise<void> {
  const filePath = objectPath(key);
  await mkdir(dirname(filePath), { recursive: true });
  await writeFile(filePath, data);
  await writeFile(metaPath(key), JSON.stringify({ contentType, bytes: data.byteLength }));
}

/** Internal helper used only by the /api/media/read route handler. */
export function localObjectPath(key: string): string {
  return objectPath(key);
}
